title: rubengm
url: "https://rubengm.com"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /writing/:title/

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
