title: rubengm
url: "https://rubengm.com"
baseurl: ""
author: Ruben GM

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /writing/:title/

collections:
  projects:
    output: true
    permalink: /projects/:title/

plugins:
 - jekyll-feed

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
